name: ExplodingPlayers
version: '1.0.1'
main: me.honeyberries.explodingPlayers.ExplodingPlayers
api-version: '1.13'
authors: [ HoneyBerries ]

commands:
  explodingPlayers:
    description: "Allows you to modify the list of players who would explode!"
    usage: "Usage: /explodingPlayers <add|remove|list|reload|power> [player]"
    aliases: [ exp ]
permissions:
  explodingPlayers.command.edit:
    description: "This permission allows users to view and edit the players that will explode!"
    default: op
  explodingPlayers.explode.use:
    description: "This permission allows users to make players EXPLODE!"
    default: true
  explodingPlayers.command.view:
    description: "Allows you to view the settings!"
    default: true
  explodingplayers.command.reload:
    description: "Allows you to reload the configuration!"
    defaut: op
